// web/src/utils/mealPlanExporter.js

/**
 * Exports the entire meal plan to a clean, human-readable text format
 * and copies it to the clipboard.
 * 
 * @param {Array} mealPlan - Array of day objects containing meals
 * @returns {Promise<{success: boolean, message: string}>}
 */
export const exportMealPlanToClipboard = async (mealPlan) => {
    try {
        // Validate input
        if (!mealPlan || !Array.isArray(mealPlan) || mealPlan.length === 0) {
            return {
                success: false,
                message: 'No meal plan data to copy'
            };
        }

        // Generate the formatted text
        const textContent = formatMealPlanAsText(mealPlan);

        // Attempt to copy to clipboard
        const copySuccess = await copyToClipboard(textContent);

        if (copySuccess) {
            return {
                success: true,
                message: 'Meal plan copied to clipboard!'
            };
        } else {
            return {
                success: false,
                message: 'Failed to copy to clipboard'
            };
        }
    } catch (error) {
        console.error('[EXPORTER] Error exporting meal plan:', error);
        return {
            success: false,
            message: 'Error copying meal plan'
        };
    }
};

/**
 * Formats the meal plan data into a clean text structure
 * 
 * @param {Array} mealPlan - Array of day objects
 * @returns {string} - Formatted text content
 */
const formatMealPlanAsText = (mealPlan) => {
    const lines = [];
    
    // Header
    lines.push('═══════════════════════════════════════════════');
    lines.push('          YOUR MEAL PLAN');
    lines.push('═══════════════════════════════════════════════');
    lines.push('');

    // Process each day
    mealPlan.forEach((day) => {
        const dayNumber = day.dayNumber || 'Unknown';
        const meals = day.meals || [];

        // Process each meal in the day
        meals.forEach((meal, mealIndex) => {
            // Skip invalid meals
            if (!meal || typeof meal !== 'object') {
                return;
            }

            // Extract meal data with defensive defaults
            const mealName = meal.name || `Meal ${mealIndex + 1}`;
            const mealType = meal.type || 'Meal';
            const description = meal.description || '';
            const instructions = Array.isArray(meal.instructions) ? meal.instructions : [];
            const items = Array.isArray(meal.items) ? meal.items : [];

            // Macros with safe fallbacks
            const kcal = Math.round(meal.subtotal_kcal || 0);
            const protein = Math.round(meal.subtotal_protein || 0);
            const fat = Math.round(meal.subtotal_fat || 0);
            const carbs = Math.round(meal.subtotal_carbs || 0);

            // Meal header
            lines.push(`Day ${dayNumber} – ${mealType}: ${mealName}`);
            lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
            
            // Macros line
            lines.push(`Macros: ${kcal} kcal | ${protein}g protein | ${fat}g fat | ${carbs}g carbs`);
            lines.push('');

            // Ingredients section
            if (items.length > 0) {
                lines.push('Ingredients:');
                items.forEach((item) => {
                    if (item && item.key) {
                        const qty = item.qty || 0;
                        const unit = item.unit || '';
                        lines.push(`  • ${qty}${unit} ${item.key}`);
                    }
                });
                lines.push('');
            }

            // Description section
            if (description) {
                lines.push('Method:');
                lines.push(description);
                lines.push('');
            }

            // Instructions section
            if (instructions.length > 0) {
                lines.push('Instructions:');
                instructions.forEach((step, index) => {
                    lines.push(`  ${index + 1}. ${step}`);
                });
                lines.push('');
            }

            // Add spacing between meals
            lines.push('');
        });
    });

    // Footer
    lines.push('═══════════════════════════════════════════════');
    lines.push('Generated by Cheffy');
    lines.push('═══════════════════════════════════════════════');

    return lines.join('\n');
};

/**
 * Attempts to copy text to clipboard using modern API with fallback
 * 
 * @param {string} text - Text content to copy
 * @returns {Promise<boolean>} - Success status
 */
const copyToClipboard = async (text) => {
    // Modern Clipboard API (preferred method)
    if (navigator.clipboard && navigator.clipboard.writeText) {
        try {
            await navigator.clipboard.writeText(text);
            return true;
        } catch (error) {
            console.warn('[EXPORTER] Clipboard API failed, trying fallback:', error);
            // Fall through to fallback method
        }
    }

    // Fallback method for older browsers
    try {
        const textArea = document.createElement('textarea');
        textArea.value = text;
        
        // Style to make it invisible
        textArea.style.position = 'fixed';
        textArea.style.top = '-9999px';
        textArea.style.left = '-9999px';
        textArea.style.opacity = '0';
        
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();

        const successful = document.execCommand('copy');
        document.body.removeChild(textArea);

        return successful;
    } catch (error) {
        console.error('[EXPORTER] Fallback copy method failed:', error);
        return false;
    }
};